version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pdfstore
      - POSTGRES_USER=varunkush
      - POSTGRES_PASSWORD=kush123

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=pdfstore
      - POSTGRES_USER=varunkush
      - POSTGRES_PASSWORD=kush123
    depends_on:
      - db
